# Generated by Django 3.2.4 on 2021-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
                ('edob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['eid'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
